import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className={styles.title1}>c</span>
          <span className={styles.title2}>a</span>
          <span className={styles.title3}>d</span>
          <span className={styles.title4}>e</span>
          <span className={styles.title5}>n</span>
          <span className={styles.title6}>c</span>
          <span className={styles.title7}>e</span>
        </h1>
      </main>
    </div>
  );
}
